### ISSUE TITLE
Nexus 5 Switching camera twice

### ISSUE THREAD

**Issue by nniicc** [commonsguy/cwac-cam2#55] opened 2015-07-26 15:35 UTC
Hey, i tried the playgroud and tried switching the camera, first time it works fine chances to front face after i try to switch back to back camera all it does is load

![screenshot_2015-07-26-17-33-57](https://cloud.githubusercontent.com/assets/5363602/8894599/bc1de9f6-33bc-11e5-9a53-bee70c5034fb.png)

**Comment by commonsguy** [comment] 2015-07-26 15:41
Duplicate of issue #40.

**Closed by commonsguy** 2015-07-26 15:41 UTC
