### ISSUE TITLE
Wrong orientation on android 6 (Marshmallow) 

### ISSUE THREAD

**Issue by Zuhair-Kj** [commonsguy/cwac-cam2#135] opened 2015-12-29 04:46 UTC
I am not sure whether this is because of the device (Nexus 5X) or the new OS version
but the camera orientation is reverted see image in link:
https://drive.google.com/file/d/0ByP6surFrliGTUtGaldPcExYQ0E/view?usp=sharing

I cannot lock the orientation because I need the correct orientation of the image.

**Comment by commonsguy** [comment] 2015-12-29 11:45
Please provide complete steps to reproduce the problem.

**Comment by Zuhair-Kj** [comment] 2015-12-30 03:27
@commonsguy 
```java
intent = new CameraActivity.IntentBuilder(QuickSellActivity.this).skipConfirm()
                            .to(tempOutputFileUri)
                            .forceClassic()
                            .build();
startActivityForResult(intent, IMAGE_CAPTURE_CODE);
```

**Comment by commonsguy** [comment] 2015-12-30 13:38
Before filing other issues, please read the contribution guidelines for [instructions on submitting bug reports](https://github.com/commonsguy/cwac-cam2/blob/master/CONTRIBUTING.md#contributing-bug-reports).

I can reproduce your problem using the `demo-playground` app, with "Save full image to file" checked, "Force classic API" checked, and everything else at their defaults, from a fresh install of that app.

**Comment by commonsguy** [comment] 2016-01-03 00:01
Duplicate of issue #130

**Closed by commonsguy** 2016-01-03 00:01 UTC
Labels: bug

**Comment by commonsguy** [comment] 2016-01-03 14:51
Try v0.4.4, as I have added the Nexus 5X to the alternative orientation algorithm whitelist, and that seems to clear up the problem.
