### ISSUE TITLE
Photo stored in wrong orientation

### ISSUE THREAD

**Issue by HishamGarout** [commonsguy/cwac-cam2#176] opened 2016-04-10 14:09 UTC
Hello,

The camera works perfectly on my phone(OnePlus 2), but when I tested it on a Samsung Note 5 the image was stored in the wrong orientation, the image was rotated 90 degrees counter clockwise. Any solution to this problem?

Regards,
Hisham

**Comment by commonsguy** [comment] 2016-04-10 14:18
Closing as duplicate of issue #15.

In the future, please follow the instructions in [the documentation](https://github.com/commonsguy/cwac-cam2#questions) for getting support with this library.

**Closed by commonsguy** 2016-04-10 14:18 UTC
