### ISSUE TITLE
Crash on Android 7.0 after taking photo

### ISSUE THREAD

**Issue by kieranmchall** [commonsguy/cwac-cam2#252] opened 2016-08-31 13:46 UTC
This happens on my Nexus 5X with Android 7.0

`cwac_cam2 E/AndroidRuntime: FATAL EXCEPTION: CameraTwoEngine
                                                                                            Process: com.riseproject.supe.release_debug:cwac_cam2, PID: 1171
                                                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                                                                                                at com.commonsware.cwac.cam2.CameraTwoEngine$RequestCaptureTransaction.capture(CameraTwoEngine.java:549)
                                                                                                at com.commonsware.cwac.cam2.CameraTwoEngine$RequestCaptureTransaction.onCaptureProgressed(CameraTwoEngine.java:532)
                                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                                at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
                                                                                                at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
                                                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                                at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by commonsguy** [comment] 2016-08-31 14:50
Duplicate of #184

**Closed by commonsguy** 2016-08-31 14:50 UTC
