### ISSUE TITLE
Images are getting displayed as landscape while taking in portrait mode

### ISSUE THREAD

**Issue by aftabsikander** [commonsguy/cwac-cam2#189] opened 2016-04-27 08:51 UTC
I am getting strange result when taking pictures in portrait mode, Picture was getting displayed in landscape. This is happening when we try to take picture while holding camera in the air (Portrait mode). I believe Camera view changes angles which are not respected while taking these type of pictures.`This same issue is happening in your demo and playground application as well`

![picture 1](https://cloud.githubusercontent.com/assets/4800511/14846794/015d6de8-0c7f-11e6-8be9-03f9f66a6f9c.jpg)

List of Devices which were used to produce this issue

**Device # 1**
```
Brand: Google
DeviceModel: Nexus 5
Product: hammerhead
Manufacturer: LGE
Android Version: 6.0.1
```
**Device # 2**

```
Brand: samsung
DeviceModel: SM-G530H
Product: fortuna3gxx
Manufacturer: samsung
Android Version: 4.4.4
```

**Device # 3**

```
Brand: samsung
DeviceModel: SM-G530H
Product: fortuna3gxx
Manufacturer: samsung
Android Version: 5.0
```

**Comment by commonsguy** [comment] 2016-04-27 10:34
Closing as duplicate of issue #15. If you feel that this is a separate issue, please explain in detail why and provide **the complete set of steps to reproduce the problem**.

**Closed by commonsguy** 2016-04-27 10:34 UTC

**Comment by aftabsikander** [comment] 2016-04-27 12:01
Its almost close to issue [#15](https://github.com/commonsguy/cwac-cam2/issues/15) I am getting `EXIF orientation` as `ExifInterface.ORIENTATION_UNDEFINED (0)`
