### ISSUE TITLE
Using android-support-v4/v7 library

### ISSUE THREAD

**Issue by sugoi-wada** [commonsguy/cwac-cam2#162] opened 2016-03-03 12:46 UTC
I think It should use `android.support.v7.app.AppCompatActivity` instead of `android.app.Activity`.
Because support library has fixed some kinds of issue.
The Fragment is also same.
It may also be good to keep both of CameraActivity and CompatCameraActivity.
How do you think about it?

**Comment by commonsguy** [comment] 2016-03-03 12:50
> Because support library has fixed some kinds of issue.

IMHO, it has created more issues than it solves.

> The Fragment is also same.

No, `appcompat-v7` requires the fragment backport.

> How do you think about it?

Sometime after this library reaches a 1.0 release, I will add a `cam2-support` module that offers `appcompat-v7` compatibility for that 1.0 release.

Closing as duplicate of issue #20.

**Closed by commonsguy** 2016-03-03 12:50 UTC
