### ISSUE TITLE
Incorrect photo's rotation when auto-rotate turn off

### ISSUE THREAD

**Issue by tplkn** [commonsguy/cwac-cam2#75] opened 2015-08-11 07:50 UTC
Original camera detect correct photo's rotate when auto-rotate turn off

Nexus 5 / android 5.1

**Comment by commonsguy** [comment] 2015-08-11 10:45
@tplkn What is the "auto-rotate" that you are referring to?

**Comment by tplkn** [comment] 2015-08-11 10:49
@commonsguy https://support.google.com/accessibility/android/answer/6006961?hl=en

**Comment by commonsguy** [comment] 2015-08-11 10:53
Right now, as is noted in issue #15, the library is not making any changes to the output of the camera itself. Hence, this is a duplicate of issue #15, insofar as the problem will be addressed at that point.

Thanks!

**Closed by commonsguy** 2015-08-11 10:53 UTC
