### ISSUE TITLE
LG GPad F (V496) Camera hangs up after opening.

### ISSUE THREAD

**Issue by Haris07** [commonsguy/cwac-cam2#133] opened 2015-12-17 10:11 UTC
Looks like camera is not initializing on this device. It hangs up and remains in this mode.
See attached image
![lg_gpad_f_v496](https://cloud.githubusercontent.com/assets/4725634/11866986/35a195dc-a4d0-11e5-99e0-afcc7a8854aa.jpg)

Also here are some logs related to camera which might help you.
W/CameraDevice-JV-0: Stream configuration failed
E/CameraDevice-0-LE: Surface with size (w=889, h=1186) and format 0x1 is not valid, size not in valid set: [1920x1440, 1920x1080, 1280x960, 1280x800, 1280x720, 1024x768, 960x720, 1024x640, 960x540, 800x600, 864x480, 704x576, 800x500, 720x540, 800x480, 720x480, 640x480, 576x432, 480x320, 384x288, 352x288, 320x240, 240x160, 176x144]
E/CameraCaptureSession: Session 0: Failed to create capture session; configuration failed

**Comment by commonsguy** [comment] 2015-12-17 11:26
@Haris07 The error you cited sounds like the one from issue #128, which I addressed in v0.4.2. Make sure that you are testing v0.4.2.

**Comment by commonsguy** [comment] 2016-02-06 22:07
Closing as not reproducible, due to lack of feedback.

**Closed by commonsguy** 2016-02-06 22:07 UTC
Labels: question
