### ISSUE TITLE
Galaxy S3 i9300 - Android 4.3: Capture Video

### ISSUE THREAD

**Issue by NhonDev91** [commonsguy/cwac-cam2#138] opened 2016-01-14 04:01 UTC
![m0xxjss15jnhonnguyen01142016111727](https://cloud.githubusercontent.com/assets/13114496/12315673/6f67d7e0-bab0-11e5-9986-c1eef365686c.png)
Capture Video with front camera, the video file i got is incorrect.

**Comment by commonsguy** [comment] 2016-01-14 12:13
Please read and follow the instructions in the contribution guidelines for [reporting problems with camera output](https://github.com/commonsguy/cwac-cam2/blob/master/CONTRIBUTING.md#bug-reports-about-camera-picture-output).

**Comment by commonsguy** [comment] 2016-02-06 22:07
Closing as not reproducible, due to lack of details.

**Closed by commonsguy** 2016-02-06 22:07 UTC
Labels: question
