### ISSUE TITLE
Lib crashes when take picture on Nexus5X device (Android N)

### ISSUE THREAD

**Issue by sergiosilvajr** [commonsguy/cwac-cam2#261] opened 2016-09-30 20:01 UTC
I have tried to use CWAC-CAM2 on a nexus 5X with Android Nougat (7.0) and after taking a pictures my app crashed.
I have tried to force Camera Classic engine (using .forceEngine(CameraEngine.ID.CLASSIC)) but without success.

Could you take a look on it ? 

Log below: 

 java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                      at com.commonsware.cwac.cam2.CameraTwoEngine$RequestCaptureTransaction.capture(CameraTwoEngine.java:549)
                      at com.commonsware.cwac.cam2.CameraTwoEngine$RequestCaptureTransaction.onCaptureProgressed(CameraTwoEngine.java:532)

**Comment by commonsguy** [comment] 2016-09-30 22:40
This is an issue tracker. Please follow [the instructions for getting support](https://github.com/commonsguy/cwac-cam2#questions).

With respect to your problem, this should have been fixed in 0.6.7 via issue #184. Please make sure that you are on 0.6.7 or higher (the latest version is 0.6.9).

Marking as duplicate of #184.

**Closed by commonsguy** 2016-09-30 22:40 UTC
