### ISSUE TITLE
Orientation issues on Samsung Galaxy S4 

### ISSUE THREAD

**Issue by andrewprocter** [commonsguy/cwac-cam2#90] opened 2015-09-08 17:52 UTC
MANUFACTURER: samsung 
PRODUCT:jfltevl

Seems like photos taken in portrait are always returned rotated 90 degrees when returned in onActivityResult. I would attach a zip of the demo app output, but the images are fine there. The behaviour can be seen in demo-playground on this device though. Screenshot:

![screenshot_2015-09-08-15-20-58](https://cloud.githubusercontent.com/assets/804169/9742833/c7109d40-5630-11e5-8e92-9f166c63463b.png)

**Comment by commonsguy** [comment] 2015-09-08 17:54
Most likely, this is a duplicate of issue #15. Examine the taken photo and see if if has an EXIF orientation header. If it does, then that's what issue #15 is for. If not, it may be a duplicate of issue #45.

**Comment by andrewprocter** [comment] 2015-09-08 17:59
Ah, they do have the orientation header: Orientation: 8 (Rotated 90° CW)

**Comment by commonsguy** [comment] 2015-09-08 18:01
Yeah, that'll be addressed by issue #15. One of the many aggravations of working with the camera APIs.

Closing as a duplicate of issue #15.

**Closed by commonsguy** 2015-09-08 18:01 UTC

**Comment by andrewprocter** [comment] 2015-09-08 18:04
I've subscribed to notifications on #15! Thanks for all your work on this.
