### ISSUE TITLE
Please let me know how to change flash mode while camera perview is on..

### ISSUE THREAD

**Issue by mobiloitte-varun-jain** [commonsguy/cwac-cam2#144] opened 2016-02-07 06:34 UTC

**Comment by commonsguy** [comment] 2016-02-07 11:47
The user will eventually be able to change flash modes -- see issue #126.

Flash modes will never be able to be changed programmatically after the activity has been launched, though. If that is what you are seeking, please work directly with the camera APIs.

Closing as a duplicate of issue #126.

**Closed by commonsguy** 2016-02-07 11:47 UTC
