### ISSUE TITLE
Failed to create capture session

### ISSUE THREAD

**Issue by dmitryduda** [commonsguy/cwac-cam2#54] opened 2015-07-24 08:57 UTC
On my LG G2 I have this Log poutput:

E/CameraDevice-0-LE﹕ Surface with size (w=1080, h=1701) and format 0x1 is not valid, size not in valid set: [2560x1440, 1920x1440, 1920x1080, 1776x1080, 1440x1080, 1280x960, 1280x720, 960x720, 864x480, 880x720, 848x480, 800x480, 768x432, 720x480, 640x480, 576x432, 480x320, 384x288, 352x288, 320x240, 240x160, 176x144, 160x120]
W/CameraDevice-JV-0﹕ Stream configuration failed
E/CameraCaptureSession﹕ Session 0: Failed to create capture session; configuration failed

The camera freazes and only indeterminate spinner is shown

**Comment by commonsguy** [comment] 2015-07-24 10:35
This is a duplicate of issue #51.

I should be releasing v0.1.1 this week for all the pending-release tagged items. This issue, and the aspect ratio ones, are next on my list to work on.

Thanks for the info!

**Closed by commonsguy** 2015-07-24 10:35 UTC
