### ISSUE TITLE
[Feature request] add flash mode for camera

### ISSUE THREAD

**Issue by tplkn** [commonsguy/cwac-cam2#67] opened 2015-08-07 10:06 UTC
1. For classic engine just put parameter in Camera.Params
```java
final Descriptor descriptor = (Descriptor) session.getDescriptor();
final Camera camera = descriptor.getCamera();
final Camera.Parameters parameters = camera.getParameters();
parameters.setFlashMode(Camera.Parameters.FLASH_MODE_...);
camera.setParameters(parameters);
```

2. for two engine can apply with CaptureRequest.Builder

**Comment by commonsguy** [comment] 2015-08-07 14:48
Duplicate of issue #11

**Closed by commonsguy** 2015-08-07 14:48 UTC
