### ISSUE TITLE
Orientation of output photo on Samsung Galaxy s4 

### ISSUE THREAD

**Issue by scottyab** [commonsguy/cwac-cam2#177] opened 2016-04-13 14:46 UTC
Using the demo-playground project on the Samsung Galaxy s4 if i take a photo in portrait the photo in preview and output is rotated. 

Video of the issue - https://www.youtube.com/watch?v=Wjes1cfZGDQ&feature=youtu.be

Manufactorure: Samsung
Model: GTI9295
Android OS version: 5.0.1

**Comment by commonsguy** [comment] 2016-04-13 14:49
Some camera modules do not actually rotate the image, but rather set the EXIF `Orientation` header, expecting image viewers to rotate the image.

For now, closing as duplicate of issue #15. If you have evidence to suggest that the `Orientation` header is not being set, let me know.

**Closed by commonsguy** 2016-04-13 14:49 UTC
