### ISSUE TITLE
OOM crash on Samsung GS5/GS6 (4.4.2) when taking Portrait photo from RFC...

### ISSUE THREAD

**Issue by jnahansen** [commonsguy/cwac-cam2#263] opened 2016-10-04 20:08 UTC
No issues in Landscape or Portrait on following phones tested (Nexus5/Nexus5X/HTC One/Droid4/Note5). Memory triples on GS5/GS6. GS4 running (5.0.1) failed w/ same error.
Strange - only fails on Samsung and only in Portrait on RFC. FFC is OK everywhere else:

10-04 13:02:34.031 12487-12498/protect.opera.com.dev D/dalvikvm: GC_FOR_ALLOC freed 3794K, 73% free 14758K/54360K, paused 28ms, total 28ms
10-04 13:02:34.066 12487-13178/protect.opera.com.dev D/dalvikvm: GC_FOR_ALLOC freed 238K, 71% free 16099K/54360K, paused 29ms, total 29ms
10-04 13:02:34.111 12487-13178/protect.opera.com.dev I/dalvikvm-heap: Grow heap (frag case) to 46.807MB for 31961104-byte allocation
10-04 13:02:34.141 12487-12496/protect.opera.com.dev D/dalvikvm: GC_FOR_ALLOC freed 0K, 13% free 47311K/54360K, paused 31ms, total 31ms
10-04 13:02:34.331 12487-13178/protect.opera.com.dev D/dalvikvm: GC_FOR_ALLOC freed 1K, 13% free 47311K/54360K, paused 24ms, total 24ms
10-04 13:02:34.331 12487-13178/protect.opera.com.dev I/dalvikvm-heap: Forcing collection of SoftReferences for 31961104-byte allocation
10-04 13:02:34.361 12487-13178/protect.opera.com.dev D/dalvikvm: GC_BEFORE_OOM freed <1K, 13% free 47311K/54360K, paused 31ms, total 31ms
10-04 13:02:34.361 12487-13178/protect.opera.com.dev E/dalvikvm-heap: Out of memory on a 31961104-byte allocation.
10-04 13:02:34.361 12487-13178/protect.opera.com.dev I/dalvikvm: "pool-12-thread-1" prio=5 tid=11 RUNNABLE
10-04 13:02:34.361 12487-13178/protect.opera.com.dev I/dalvikvm:   | group="main" sCount=0 dsCount=0 obj=0x424b59e0 self=0x61f173b0
10-04 13:02:34.361 12487-13178/protect.opera.com.dev I/dalvikvm:   | sysTid=13178 nice=0 sched=0/0 cgrp=apps handle=1763524424
10-04 13:02:34.366 12487-13178/protect.opera.com.dev I/dalvikvm:   | state=R schedstat=( 709373223 855680745 502 ) utm=58 stm=12 core=3
10-04 13:02:34.366 12487-13178/protect.opera.com.dev I/dalvikvm:     at android.graphics.Bitmap.nativeCreate(Native Method)
10-04 13:02:34.366 12487-13178/protect.opera.com.dev I/dalvikvm:     at android.graphics.Bitmap.createBitmap(Bitmap.java:928)
10-04 13:02:34.366 12487-13178/protect.opera.com.dev I/dalvikvm:     at android.graphics.Bitmap.createBitmap(Bitmap.java:901)
10-04 13:02:34.366 12487-13178/protect.opera.com.dev I/dalvikvm:     at android.graphics.Bitmap.createBitmap(Bitmap.java:833)
10-04 13:02:34.366 12487-13178/protect.opera.com.dev I/dalvikvm:     at com.commonsware.cwac.cam2.ImageContext.rotateViaMatrix(ImageContext.java:251)
10-04 13:02:34.366 12487-13178/protect.opera.com.dev I/dalvikvm:     at com.commonsware.cwac.cam2.ImageContext.getJpeg(ImageContext.java:104)
10-04 13:02:34.366 12487-13178/protect.opera.com.dev I/dalvikvm:     at com.commonsware.cwac.cam2.JPEGWriter.process(JPEGWriter.java:84)
10-04 13:02:34.366 12487-13178/protect.opera.com.dev I/dalvikvm:     at com.commonsware.cwac.cam2.PictureTransaction.process(PictureTransaction.java:38)
10-04 13:02:34.366 12487-13178/protect.opera.com.dev I/dalvikvm:     at com.commonsware.cwac.cam2.ClassicCameraEngine$TakePictureTransaction$1.run(ClassicCameraEngine.java:484)
10-04 13:02:34.366 12487-13178/protect.opera.com.dev I/dalvikvm:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-04 13:02:34.366 12487-13178/protect.opera.com.dev I/dalvikvm:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-04 13:02:34.366 12487-13178/protect.opera.com.dev I/dalvikvm:     at java.lang.Thread.run(Thread.java:841)
10-04 13:02:34.366 12487-13178/protect.opera.com.dev E/CWAC-Cam2: Exception in camera processing
                                                                  java.lang.OutOfMemoryError
                                                                      at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                      at android.graphics.Bitmap.createBitmap(Bitmap.java:928)
                                                                      at android.graphics.Bitmap.createBitmap(Bitmap.java:901)
                                                                      at android.graphics.Bitmap.createBitmap(Bitmap.java:833)
                                                                      at com.commonsware.cwac.cam2.ImageContext.rotateViaMatrix(ImageContext.java:251)
                                                                      at com.commonsware.cwac.cam2.ImageContext.getJpeg(ImageContext.java:104)
                                                                      at com.commonsware.cwac.cam2.JPEGWriter.process(JPEGWriter.java:84)
                                                                      at com.commonsware.cwac.cam2.PictureTransaction.process(PictureTransaction.java:38)
                                                                      at com.commonsware.cwac.cam2.ClassicCameraEngine$TakePictureTransaction$1.run(ClassicCameraEngine.java:484)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:841)
10-04 13:02:34.401 12487-12487/protect.opera.com.dev I/ParentDashboard: onActivityResult: requestCode: 1339
10-04 13:02:34.401 12487-12487/protect.opera.com.dev W/ParentDashboard: onActivityResult: resultCode CANCELED: 0

**Comment by commonsguy** [comment] 2016-10-05 12:30
Closing as duplicate of issue #256

**Closed by commonsguy** 2016-10-05 12:30 UTC
