### ISSUE TITLE
Nexus 5X Compatibility

### ISSUE THREAD

**Issue by georgelin422** [commonsguy/cwac-cam2#134] opened 2015-12-23 08:16 UTC
I tried to run samples on Google Nexus 5X LGE/bullhead Android 6.0 and it seems to fail when sending intent to start Cam2 Activity with rear camera.

error log:
`cwac_cam2 E/CameraCaptureSession: Session 0: Failed to create capture session; configuration failed`

**Comment by commonsguy** [comment] 2015-12-23 12:27
Please provide the complete steps to reproduce the crash. Thanks!

On Wed, Dec 23, 2015, at 03:16, George Lin wrote:
> I tried to run samples on Google Nexus 5X LGE/bullhead Android 6.0 and it
> seems to fail when sending intent to start Cam2 Activity with rear
> camera.
> 
> error log:
> `cwac_cam2 E/CameraCaptureSession: Session 0: Failed to create capture
> session; configuration failed`
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/commonsguy/cwac-cam2/issues/134


-- 
Mark Murphy (a Commons Guy)
https://commonsware.com | https://github.com/commonsguy
https://commonsware.com/blog | https://twitter.com/commonsguy

**Comment by hijamoya** [comment] 2015-12-24 13:36
Same issue. 
Step:
1. find a  Nexus 5X LGE/bullhead
2. install play ground
3. try to launch the back camera.
4. fail to launch

**Comment by commonsguy** [comment] 2015-12-26 14:26
Neither bug report noted that the actual problem can only be reproduced in portrait mode with the rear-facing camera. Can be seen in `demo/` and `demo-playground/`.

**Comment by commonsguy** [comment] 2015-12-26 19:30
Seems to be an issue of too large of a preview size. I have added some caps that clears up the problem. The bug fix will be released tomorrow, barring unforeseen circumstances.

**Comment by commonsguy** [comment] 2015-12-27 17:22
Addressed in v0.4.3.

**Closed by commonsguy** 2015-12-27 17:22 UTC
Labels: bug, pending-release
